server:
  port: 9411
  pring:
    rabbitmq:
      host: localhost
      port: 15672
      username: guest
      password: guest
zipkin:
  storage:
    type: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver