eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: feign
    #开启熔断器
    feign:
      hystrix:
        enabled: true